### ISSUE TITLE
Python build issues

### ISSUE THREAD

**Issue by Divide-By-0** [toastpp/toastpp#76]
Python build from source fails for me on MacOS due to:
```
INFO: clang++ -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/username/miniconda3/lib -L/Users/username/miniconda3/lib -Wl,-rpath,/Users/username/miniconda3/lib -L/Users/username/miniconda3/lib build/temp.macosx-11.1-arm64-cpython-311/toastmodule.o -L/Users/username/project/toastpp/src/python/../../lib -Wl,-rpath,/Users/username/project/toastpp/src/python/../../lib -lmath -lfe -lstoast -o build/lib.macosx-11.1-arm64-cpython-311/toast/toastmod.cpython-311-darwin.so
ld: library not found for -lmath
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have no idea what math library it refers to, as the library here is called libmath not math, and within the python files, the math import isn't even being used.

The compiled releases do not contain a Python package in the Darwin bundle. In addition, the commit history seems to have a Python3 commit, but all the releases are 2.7. 

To build the Linux build of Python on ARM, I had to compile numpy via miniconda on conda-forge's python 2.7. Then, I get this error:
```
Traceback (most recent call last):
  File "toast_bin_linux64/test.py", line 3, in <module>
    import toast
  File "/home/username/toastpp/toast_bin_linux64/linux64/lib/python2.7/site-packages/toast/__init__.py", line 1, in <module>
    from mesh import Mesh
  File "/home/username/toastpp/toast_bin_linux64/linux64/lib/python2.7/site-packages/toast/mesh.py", line 3, in <module>
    from toast import toastmod
ImportError: /home/username/toastpp/toast_bin_linux64/linux64/lib/python2.7/site-packages/toast/toastmod.so: cannot open shared object file: No such file or directory
```

Even though there seems to be a setup.py and compiled binaries, there is no pip package published. It would be awesome for any one of these issues to be fixed, and for there to be a compiled .whl uploaded somwhere, as then others could use this package.

**Comment by samuelpowell** [comment]
I maintain a fork, [toastmm](https://github.com/samuelpowell/toastmm), which provides an updated build system. There are some minor changes to the Python interface, but it should build cleanly locally.
